databases:
  - name: lifeinweeks_db
    databaseName: lifeinweeks
    user: lifeinweeks_user
    plan: free

services:
  - type: web
    name: lifeinweeks
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:create_app()"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lifeinweeks_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
